language: ruby
sudo: false
cache: bundler

# Bundler/RubyGems incompat on Ruby 2.5.0 and 2.6.1
before_install: gem update --system && gem install bundler -v 1.17.3

rvm:
  - 2.6
  - 2.7
  - 3.0
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
